---
- name: Mettre à jour les paquets APT
  apt:
    update_cache: yes

- name: Installer Apache2
  apt:
    name: apache2
    state: present


- name: Redémarrer Apache2
  service:
    name: apache2
    state: restarted
