---
- name: Télécharger la dernière version de WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Copier le fichier de configuration wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    mode: '0644'

- name: Changer les permissions sur le répertoire WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: www-data
    group: www-data
    recurse: yes