---
- name: Installer les dépendances nécessaires
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - lsb-release
    - ca-certificates
    - gnupg

- name: Ajouter la clé GPG pour le dépôt sury.org
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Ajouter le dépôt sury.org pour PHP
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: Mettre à jour les paquets APT
  apt:
    update_cache: yes

- name: Installer PHP 8.1 et les modules courants
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php8.1
    - libapache2-mod-php8.1
    - php8.1-cli
    - php8.1-fpm
    - php8.1-mysql
    - php8.1-curl
    - php8.1-cgi
    - php8.1-mbstring
    - php8.1-xml
    - php8.1-zip