---
- name: Ajouter le repository pour PHP 8.1
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Mettre à jour les paquets APT après ajout du repository
  apt:
    update_cache: yes

- name: Installer PHP 8.1 et les modules courants
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php8.1
    - libapache2-mod-php8.1
    - php8.1-cli
    - php8.1-fpm
    - php8.1-mysql
    - php8.1-curl
    - php8.1-json
    - php8.1-cgi
    - php8.1-mbstring
    - php8.1-xml
    - php8.1-zip